# Generated by Django 4.1.5 on 2023-08-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_postmodel_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
