# Generated by Django 4.1.5 on 2023-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_postmodel_options_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/upload'),
        ),
    ]
