# Generated by Django 4.1.5 on 2023-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/upload'),
        ),
    ]
