# Generated by Django 4.1.5 on 2023-08-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_postmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='image',
        ),
    ]
