# Generated by Django 4.1.5 on 2023-08-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_remove_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
